---
- name: reload daemons
  shell: systemctl daemon-reload

- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted